from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from textwrap import dedent


PLUGIN_ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")
VERSION = "0.1.0"
PLUGIN_TYPES = {"sql", "c"}


@dataclass(frozen=True, slots=True)
class DevInitResult:
    plugin_id: str
    target_dir: Path
    files: tuple[Path, ...]
    plugin_type: str = "sql"


def validate_plugin_id(plugin_id: str) -> None:
    if not PLUGIN_ID_RE.fullmatch(plugin_id):
        raise ValueError(f"Invalid plugin_id: {plugin_id}\nplugin_id must match: ^[a-z][a-z0-9_]*$")


def validate_plugin_type(plugin_type: str) -> str:
    normalized = plugin_type.lower()
    if normalized not in PLUGIN_TYPES:
        raise ValueError("plugin type must be one of: sql, c")
    return normalized


def _write(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"target file already exists: {path}; use --force to overwrite generated files")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _manifest(plugin_id: str, plugin_type: str) -> str:
    if plugin_type == "c":
        return _c_manifest(plugin_id)
    return _sql_manifest(plugin_id)


def _sql_manifest(plugin_id: str) -> str:
    return dedent(
        f"""\
        plugin_id: {plugin_id}
        name: {plugin_id} Plugin
        version: "{VERSION}"
        description: SQL-only plugin skeleton generated by PluginCtl new.
        extension: {plugin_id}
        type: sql
        database: OpenTenBase
        targets:
          cn: true
          dn: true

        distributed:
          required_roles:
            - coordinator
          probe_strategy: coordinator
          notes: "SQL-only starter extension; CREATE EXTENSION is executed through the primary coordinator."

        extension_files:
          - {plugin_id}.control
          - sql/{plugin_id}--{VERSION}.sql

        payload:
          source_root: .
          extension_name: {plugin_id}
          install_sql: sql/{plugin_id}--{VERSION}.sql
          verify_sql: sql/verify.sql
          smoke_sql: sql/verify.sql
          rollback_sql: sql/rollback.sql
          installed_probe: SELECT extversion FROM pg_extension WHERE extname = '{plugin_id}';
          removed_probe: SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = '{plugin_id}') AND NOT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = '{plugin_id}') THEN 'removed' ELSE 'present' END;

        verify_sql: sql/verify.sql
        rollback_sql: sql/rollback.sql

        notes:
          - Generated by plugin_ctl new.
          - This is a SQL-only starter plugin; it does not require compilation.
        """
    )


def _c_manifest(plugin_id: str) -> str:
    return dedent(
        f"""\
        plugin_id: {plugin_id}
        name: {plugin_id} C Plugin
        version: "{VERSION}"
        description: C plugin skeleton generated by PluginCtl new -c.
        extension: {plugin_id}
        type: c
        database: OpenTenBase
        targets:
          cn: true
          dn: true

        distributed:
          required_roles:
            - coordinator
            - datanode
          probe_strategy: coordinator
          notes: "C extension files must be built before deploy and distributed to CN/DN nodes."

        source_files:
          - src/{plugin_id}.c
          - Makefile

        extension_files:
          - {plugin_id}.control
          - sql/{plugin_id}--{VERSION}.sql

        library_files:
          - {plugin_id}.so

        build:
          system: pgxs
          workdir: .
          pg_config: auto

        payload:
          source_root: .
          extension_name: {plugin_id}
          install_sql: sql/{plugin_id}--{VERSION}.sql
          verify_sql: sql/verify.sql
          smoke_sql: sql/verify.sql
          rollback_sql: sql/rollback.sql
          installed_probe: SELECT extversion FROM pg_extension WHERE extname = '{plugin_id}';
          removed_probe: SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = '{plugin_id}') THEN 'removed' ELSE 'present' END;
          requires_build: true
          extension_files:
            - {plugin_id}.control
            - sql/{plugin_id}--{VERSION}.sql
          library_files:
            - {plugin_id}.so

        verify_sql: sql/verify.sql
        rollback_sql: sql/rollback.sql

        notes:
          - Generated by plugin_ctl new -c.
          - Run plugin_ctl build {plugin_id} before deploy.
        """
    )


def _control(plugin_id: str, plugin_type: str) -> str:
    if plugin_type == "c":
        return dedent(
            f"""\
            comment = '{plugin_id} C extension'
            default_version = '{VERSION}'
            module_pathname = '$libdir/{plugin_id}'
            relocatable = true
            """
        )
    return dedent(
        f"""\
        comment = '{plugin_id} extension generated by PluginCtl'
        default_version = '{VERSION}'
        relocatable = true
        """
    )


def _install_sql(plugin_id: str, plugin_type: str) -> str:
    if plugin_type == "c":
        return dedent(
            f"""\
            CREATE FUNCTION hello()
            RETURNS text
            AS 'MODULE_PATHNAME', '{plugin_id}'
            LANGUAGE C
            STRICT;
            """
        )
    return dedent(
        f"""\
        CREATE SCHEMA IF NOT EXISTS {plugin_id};

        CREATE OR REPLACE FUNCTION {plugin_id}.hello()
        RETURNS text
        LANGUAGE sql
        AS $$
            SELECT 'hello from {plugin_id}';
        $$;
        """
    )


def _verify_sql(plugin_id: str, plugin_type: str) -> str:
    if plugin_type == "c":
        return "SELECT hello();\n"
    return dedent(
        f"""\
        SELECT {plugin_id}.hello();

        SELECT n.nspname AS schema_name,
               p.proname AS function_name
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = '{plugin_id}'
          AND p.proname = 'hello';
        """
    )


def _rollback_sql(plugin_id: str, plugin_type: str) -> str:
    if plugin_type == "c":
        return dedent(
            f"""\
            DROP EXTENSION IF EXISTS {plugin_id} CASCADE;
            DROP FUNCTION IF EXISTS hello();
            """
        )
    return dedent(
        f"""\
        DROP EXTENSION IF EXISTS {plugin_id} CASCADE;
        DROP SCHEMA IF EXISTS {plugin_id} CASCADE;
        """
    )


def _c_source(plugin_id: str) -> str:
    return dedent(
        f"""\
        #include "postgres.h"
        #include "fmgr.h"
        #include "utils/builtins.h"

        PG_MODULE_MAGIC;

        PG_FUNCTION_INFO_V1({plugin_id});

        Datum
        {plugin_id}(PG_FUNCTION_ARGS)
        {{
            PG_RETURN_TEXT_P(cstring_to_text("hello_world"));
        }}
        """
    )


def _makefile(plugin_id: str) -> str:
    return dedent(
        f"""\
        EXTENSION = {plugin_id}
        MODULE_big = {plugin_id}
        OBJS = src/{plugin_id}.o
        DATA = sql/{plugin_id}--{VERSION}.sql

        PG_CONFIG ?= pg_config
        PGXS := $(shell $(PG_CONFIG) --pgxs)
        include $(PGXS)
        """
    )


def _readme(plugin_id: str, plugin_type: str) -> str:
    if plugin_type == "c":
        build = f"\n## Build\n\n```bash\nplugin_ctl build {plugin_id}\n```\n\n`build` uses PGXS and does not run `make install`.\n"
    else:
        build = "\nThis is a SQL-only plugin and does not require compilation.\n"
    return dedent(
        f"""\
        # {plugin_id}

        Generated by PluginCtl.
        {build}
        ## Next steps

        ```bash
        plugin_ctl
        pluginctl> init
        pluginctl> deploy {plugin_id}
        pluginctl> register {plugin_id}
        pluginctl> check {plugin_id}
        pluginctl> quit
        ```
        """
    )


def _ignore() -> str:
    return dedent(
        """\
        __pycache__/
        *.pyc
        .DS_Store
        .git/
        dist/
        build/
        *.o
        *.bc
        """
    )


def generated_relative_paths(plugin_id: str, plugin_type: str = "sql") -> tuple[Path, ...]:
    common = (
        Path("README.md"),
        Path("manifest.yml"),
        Path(f"{plugin_id}.control"),
        Path("sql") / f"{plugin_id}--{VERSION}.sql",
        Path("sql") / "verify.sql",
        Path("sql") / "rollback.sql",
        Path(".pluginctlignore"),
    )
    if validate_plugin_type(plugin_type) == "c":
        return (
            Path("README.md"),
            Path("manifest.yml"),
            Path("Makefile"),
            Path(f"{plugin_id}.control"),
            Path("src") / f"{plugin_id}.c",
            Path("sql") / f"{plugin_id}--{VERSION}.sql",
            Path("sql") / "verify.sql",
            Path("sql") / "rollback.sql",
            Path(".pluginctlignore"),
        )
    return common


def create_plugin_skeleton(
    plugin_id: str,
    *,
    base_dir: Path | None = None,
    force: bool = False,
    plugin_type: str = "sql",
) -> DevInitResult:
    validate_plugin_id(plugin_id)
    plugin_type = validate_plugin_type(plugin_type)
    target_dir = (base_dir or Path.cwd()) / plugin_id
    target_dir = target_dir.expanduser()

    if target_dir.exists() and not force:
        raise FileExistsError(f"target directory already exists: {target_dir}; use --force to overwrite generated files")

    files = {
        Path("README.md"): _readme(plugin_id, plugin_type),
        Path("manifest.yml"): _manifest(plugin_id, plugin_type),
        Path(f"{plugin_id}.control"): _control(plugin_id, plugin_type),
        Path("sql") / f"{plugin_id}--{VERSION}.sql": _install_sql(plugin_id, plugin_type),
        Path("sql") / "verify.sql": _verify_sql(plugin_id, plugin_type),
        Path("sql") / "rollback.sql": _rollback_sql(plugin_id, plugin_type),
        Path(".pluginctlignore"): _ignore(),
    }
    if plugin_type == "c":
        files[Path("Makefile")] = _makefile(plugin_id)
        files[Path("src") / f"{plugin_id}.c"] = _c_source(plugin_id)

    for rel_path, content in files.items():
        _write(target_dir / rel_path, content, force=force)

    return DevInitResult(plugin_id=plugin_id, target_dir=target_dir, files=tuple(files.keys()), plugin_type=plugin_type)
