from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from textwrap import dedent


PLUGIN_ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")
VERSION = "0.1.0"


@dataclass(frozen=True, slots=True)
class DevInitResult:
    plugin_id: str
    target_dir: Path
    files: tuple[Path, ...]


def validate_plugin_id(plugin_id: str) -> None:
    if not PLUGIN_ID_RE.fullmatch(plugin_id):
        raise ValueError(
            f"Invalid plugin_id: {plugin_id}\n"
            "plugin_id must match: ^[a-z][a-z0-9_]*$"
        )


def _write(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"target file already exists: {path}; use --force to overwrite generated files")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _manifest(plugin_id: str) -> str:
    return dedent(
        f"""\
        # PluginCtl 插件清单文件。
        # PluginCtl 通过这个文件识别插件 ID、版本、扩展名、需要分发的文件、验证 SQL 和回滚 SQL。

        # 插件唯一 ID，建议和目录名保持一致。
        plugin_id: {plugin_id}

        # 插件显示名称。
        name: {plugin_id} Plugin

        # 插件版本，建议和 .control 文件里的 default_version 保持一致。
        version: {VERSION}

        # 插件说明。
        description: Plugin skeleton generated by PluginCtl dev init.

        # PostgreSQL / OpenTenBase 扩展名。
        # 通常和 plugin_id 一致，CREATE EXTENSION 时会使用这个名称。
        extension: {plugin_id}

        # 当前模板面向 OpenTenBase。
        database: OpenTenBase

        # 目标节点类型。扩展 control/sql 文件通常需要在 CN 和 DN 上保持一致。
        targets:
          cn: true
          dn: true

        # 分布式治理声明。
        distributed:
          required_roles:
            - coordinator
          probe_strategy: coordinator
          notes: "SQL-only starter extension; CREATE EXTENSION is executed through the primary coordinator."

        # 插件载荷声明。
        payload:
          # source_root 是物理文件扫描和分发的根目录；这里使用插件目录本身。
          source_root: .

          # PostgreSQL / OpenTenBase extension 名称。
          extension_name: {plugin_id}

          # register 阶段执行 CREATE EXTENSION 时，数据库会读取这个安装 SQL。
          install_sql: sql/{plugin_id}--{VERSION}.sql

          # verify 阶段执行的 SQL。
          verify_sql: sql/verify.sql
          smoke_sql: sql/verify.sql

          # rollback 阶段执行的 SQL。
          rollback_sql: sql/rollback.sql

          # 判断插件是否已注册；有返回值表示已安装，无返回值表示未安装。
          installed_probe: SELECT extversion FROM pg_extension WHERE extname = '{plugin_id}';

          # verify --removed 使用的移除验证探针。
          removed_probe: SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = '{plugin_id}') AND NOT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = '{plugin_id}') THEN 'removed' ELSE 'present' END;

        notes:
          - Generated by plugin_ctl dev init.
          - This is a SQL-only starter plugin; it does not generate or compile .so files.
        """
    )


def _control(plugin_id: str) -> str:
    return dedent(
        f"""\
        # 这是 PostgreSQL / OpenTenBase extension control 文件。
        # 数据库通过这个文件识别扩展是否存在。
        # 该文件最终应放到 extension_dir 目录：
        #   $(pg_config --sharedir)/extension
        #
        # 注意：
        # 1. 文件名必须是：扩展名.control
        # 2. default_version 要和 SQL 文件名中的版本一致
        # 3. 例如 default_version = '{VERSION}' 时，
        #    安装 SQL 文件通常是：{plugin_id}--{VERSION}.sql

        comment = '{plugin_id} extension generated by PluginCtl'
        default_version = '{VERSION}'
        relocatable = true
        """
    )


def _install_sql(plugin_id: str) -> str:
    return dedent(
        f"""\
        -- 这是插件安装 SQL。
        -- 当执行 CREATE EXTENSION {plugin_id}; 时，数据库会执行这个文件。
        --
        -- 你可以在这里创建：
        -- 1. schema
        -- 2. SQL 函数
        -- 3. 类型
        -- 4. 视图
        -- 5. 表
        -- 6. 操作符
        --
        -- 第一版模板只创建一个简单的 schema 和 hello 函数，方便验证插件流程。

        CREATE SCHEMA IF NOT EXISTS {plugin_id};

        CREATE OR REPLACE FUNCTION {plugin_id}.hello()
        RETURNS text
        LANGUAGE sql
        AS $$
            SELECT 'hello from {plugin_id}';
        $$;
        """
    )


def _verify_sql(plugin_id: str) -> str:
    return dedent(
        f"""\
        -- 这是 PluginCtl verify 阶段使用的验证 SQL。
        -- 目标是确认插件对象已经创建，并且基础函数可以正常执行。

        SELECT {plugin_id}.hello();

        SELECT n.nspname AS schema_name,
               p.proname AS function_name
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = '{plugin_id}'
          AND p.proname = 'hello';
        """
    )


def _rollback_sql(plugin_id: str) -> str:
    return dedent(
        f"""\
        -- 这是 PluginCtl rollback 阶段使用的回滚 SQL。
        -- 目标是撤销该插件创建的数据库对象。
        --
        -- 注意：
        -- 1. rollback 通常只撤销数据库对象。
        -- 2. rollback 不一定删除已经分发到 CN / DN 节点上的物理文件。
        -- 3. 如果插件已经通过 CREATE EXTENSION 注册，可以先 DROP EXTENSION。

        DROP EXTENSION IF EXISTS {plugin_id} CASCADE;
        DROP SCHEMA IF EXISTS {plugin_id} CASCADE;
        """
    )


def _readme(plugin_id: str) -> str:
    return dedent(
        f"""\
        # {plugin_id}

        这是由 PluginCtl 自动生成的 OpenTenBase 插件模板。

        ## 目录说明

        - `manifest.yml`：PluginCtl 使用的插件清单文件。
        - `{plugin_id}.control`：OpenTenBase / PostgreSQL extension control 文件。
        - `sql/{plugin_id}--{VERSION}.sql`：执行 `CREATE EXTENSION {plugin_id};` 时使用的安装 SQL。
        - `sql/verify.sql`：PluginCtl verify 阶段使用的验证 SQL。
        - `sql/rollback.sql`：PluginCtl rollback 阶段使用的回滚 SQL。
        - `.pluginctlignore`：PluginCtl 打包或扫描时可忽略的文件规则。

        ## 插件文件最终会放在哪里？

        OpenTenBase / PostgreSQL 一般通过以下目录发现 extension：

        - `.control` 和 `.sql` 文件：
          - `$(pg_config --sharedir)/extension`
        - `.so` 文件：
          - `$(pg_config --pkglibdir)`

        在 OpenTenBase 分布式环境中，CN / DN 节点都需要保持插件文件一致。

        ## 下一步

        ```bash
        plugin_ctl add ./{plugin_id}
        plugin_ctl check {plugin_id}
        plugin_ctl deploy {plugin_id}
        plugin_ctl register {plugin_id}
        plugin_ctl verify {plugin_id}
        plugin_ctl report
        ```

        ## 回滚测试

        ```bash
        plugin_ctl rollback {plugin_id} --dry-run
        plugin_ctl rollback {plugin_id}
        plugin_ctl verify {plugin_id} --removed
        ```
        """
    )


def _ignore() -> str:
    return dedent(
        """\
        # PluginCtl 忽略文件。
        # 这里可以写不希望被插件打包、扫描或归档的文件。

        __pycache__/
        *.pyc
        .DS_Store
        .git/
        dist/
        build/
        """
    )


def generated_relative_paths(plugin_id: str) -> tuple[Path, ...]:
    return (
        Path("README.md"),
        Path("manifest.yml"),
        Path(f"{plugin_id}.control"),
        Path("sql") / f"{plugin_id}--{VERSION}.sql",
        Path("sql") / "verify.sql",
        Path("sql") / "rollback.sql",
        Path(".pluginctlignore"),
    )


def create_plugin_skeleton(plugin_id: str, *, base_dir: Path | None = None, force: bool = False) -> DevInitResult:
    validate_plugin_id(plugin_id)
    target_dir = (base_dir or Path.cwd()) / plugin_id
    target_dir = target_dir.expanduser()

    if target_dir.exists() and not force:
        raise FileExistsError(f"target directory already exists: {target_dir}; use --force to overwrite generated files")

    files = {
        Path("README.md"): _readme(plugin_id),
        Path("manifest.yml"): _manifest(plugin_id),
        Path(f"{plugin_id}.control"): _control(plugin_id),
        Path("sql") / f"{plugin_id}--{VERSION}.sql": _install_sql(plugin_id),
        Path("sql") / "verify.sql": _verify_sql(plugin_id),
        Path("sql") / "rollback.sql": _rollback_sql(plugin_id),
        Path(".pluginctlignore"): _ignore(),
    }
    for rel_path, content in files.items():
        _write(target_dir / rel_path, content, force=force)

    return DevInitResult(
        plugin_id=plugin_id,
        target_dir=target_dir,
        files=tuple(files.keys()),
    )
